const accounts=[['Checking','checking','$12,480.22'],['Savings','savings','$28,904.10'],['Business Checking','business','$84,220.00'],['Business Savings','business-savings','$112,540.90'],['Credit','credit','Locked'],['Business Credit','business-credit','Locked'],['IRA','ira','$41,320.17']];
const app=document.getElementById('app');let signedIn=false;
function page(){let p=location.hash.slice(1)||'dashboard';if(!signedIn&&p!=='signin')return signin();({dashboard,accounts:accountsPage,wallet,security,pos}[p]||dashboard)();}
function shell(title,body){app.innerHTML=`<div class="wrap"><div class="hero"><h1>${title}</h1></div>${body}</div>`}
function dashboard(){shell('Dashboard',`<div class="grid">${accounts.map(a=>`<div class="card account"><div><b>${a[0]}</b><div class="muted">${a[2]}</div></div><span class="pill">${a[1]}</span></div>`).join('')}</div><br><div class="card"><h2>Quick actions</h2><div class="actions"><a class="btn" href="#wallet">Wallet</a><a class="btn" href="#security">Security Center</a><a class="btn" href="#pos">Business POS</a></div></div>`)}
function accountsPage(){shell('Accounts',`<div class="grid">${accounts.map(a=>`<div class="card"><h3>${a[0]}</h3><p class="muted">${a[1]}</p><h2>${a[2]}</h2><button onclick="alert('Account actions require the authenticated Bonds Bank API.')">Manage</button></div>`).join('')}</div>`)}
function wallet(){shell('Wallet',`<div class="grid"><div class="card"><h2>Connected bank accounts</h2><p class="muted">Tokenized connections; credentials are handled by the approved account-linking provider.</p><button onclick="alert('Connect Bank Account → provider authorization flow')">+ Connect bank account</button></div><div class="card"><h2>Connected cards</h2><p class="muted">Only tokenized card references and masked details are retained. CVV is never stored.</p><button onclick="alert('Add Card → approved card tokenization flow')">+ Add card</button></div></div>`)}
function security(){shell('Security Center',`<div class="grid"><div class="card"><h3>Identity</h3><p>Optional until credit access is requested.</p><button>Verify ID + SSN</button></div><div class="card"><h3>Phone</h3><p>Verify your phone number.</p><button>Verify phone</button></div><div class="card"><h3>Two-step authentication</h3><p>Authenticator/passkey enrollment.</p><button>Set up 2-step</button></div><div class="card"><h3>Credit access</h3><p>Credit and Business Credit unlock only after identity, phone, and 2-step requirements are server-verified.</p><span class="pill">Locked</span></div></div>`)}
function pos(){shell('Business POS',`<div class="card"><h2>POS</h2><p>Available to verified Business Checking merchants. Business Checking is the default settlement account.</p><div class="actions"><button>Start terminal</button><button>Refund</button><button>View transactions</button></div></div>`)}
function signin(){app.innerHTML=`<div class="wrap"><div class="card" style="max-width:460px;margin:70px auto"><img src="assets/lion_icon.png" style="width:100px"><h1>Welcome to Bonds Bank</h1><p class="muted">Sign in or create an account.</p><div class="actions"><button onclick="login('Google')">Continue with Google</button><button onclick="login('Apple')">Continue with Apple</button><button onclick="login('Yahoo')">Continue with Yahoo</button></div><hr><label>Email</label><input id="email" type="email" placeholder="you@example.com"><button onclick="login('Email')">Continue with email</button><p class="muted">Provider credentials and tokens are handled server-side.</p></div></div>`}
function login(provider){signedIn=true;location.hash='dashboard';alert(`Demo UI: ${provider} authentication must be connected to the production identity provider.`)}
document.getElementById('authBtn').onclick=()=>{signedIn=false;location.hash='signin'};addEventListener('hashchange',page);page();
